language: python
sudo: false
cache: false
python:
    - '2.7'
os:
    - linux
    - osx
env:
  global:
    PYTHONUNBUFFERED=yes
  matrix:
    - TOXENV=2.7
    - TOXENV=3.4
    - TOXENV=pypy
    - TOXENV=3.5
    - TOXENV=pypy3
    - TOXENV=flake8
    - TOXENV=flakeplus
    - TOXENV=apicheck
install: travis_retry pip install -U tox
script: tox -v -- -v
after_success:
  - .tox/$TRAVIS_PYTHON_VERSION/bin/coverage xml
  - .tox/$TRAVIS_PYTHON_VERSION/bin/codecov -e TOXENV
